/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgetbuddy;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author morganmacdonald
 */
public class BudgetBuddyFrame extends javax.swing.JFrame {
    
    int Statement;
    int Expense;
    int Purchase;
    int Allowance;
    
    public Connection conn = null;
    
    public Connection getConn() {
        
        try {
            Class.forName("org.postgresql.Driver");
        } catch (ClassNotFoundException classNotFoundException) {
            JOptionPane.showMessageDialog(null, classNotFoundException);
        }
        
        try {
            String url = "jdbc:postgresql://localhost:5432/Budget Builder";
            String user = "postgres";
            String password = "gar18";
            
            conn = DriverManager.getConnection(url, user, password);
            JOptionPane.showMessageDialog(null, "Connected");
            
        } catch (SQLException ex) {
            Logger.getLogger(BudgetBuddyFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return conn;
    }
    
    
    
    /**
     * Creates new form BudgetBuddyFrame
     */
    public BudgetBuddyFrame() {
        initComponents();
        show_trans();
        getConn();
        this.setLocationRelativeTo(null);
        jPanel1.setBackground(new Color(0,0,0,200));
        //jPanel4.setBackground(new Color(0,0,0,200));
    }
    
    public ArrayList<User> TransactionList(){
        ArrayList<User> TransactionList = new ArrayList<>();
        try{
           Class.forName("org.postgresql.Driver");
           String url = "jdbc:postgresql://localhost:5432/Budget Builder";
           String user = "postgres";
           String password = "gar18";
            
           conn = DriverManager.getConnection(url, user, password);
           String query1 = "SELECT * FROM public.\"Transactions\";";
           Statement st = conn.createStatement();
           ResultSet rs = st.executeQuery(query1);
           User user1;
           while(rs.next()){
               user1 = new User(rs.getInt("TransactionId"), rs.getInt("Amount"), rs.getString("OneTimeName"), rs.getInt("UserId"), rs.getString("Category"), rs.getInt("Date"));
               TransactionList.add(user1);
               
           }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        return TransactionList;
    }
    
    public void show_trans(){
        ArrayList<User> list = TransactionList();
        DefaultTableModel model = (DefaultTableModel)HistoryTable.getModel();
        Object[] row = new Object[6];
        for(int i=0; i<list.size(); i++){
            row[0] = list.get(i).getTransactionId();
            row[1] = list.get(i).getAmount();
            row[2] = list.get(i).getOneTimeName();
            row[3] = list.get(i).getUserId();
            row[4] = list.get(i).getCategory();
            row[5] = list.get(i).getDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        RId = new javax.swing.JFormattedTextField();
        RSave = new javax.swing.JButton();
        MonthlyStatementLabel = new javax.swing.JLabel();
        StatementDateLabel = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        StatementDateLabel2 = new javax.swing.JLabel();
        SourceName = new javax.swing.JFormattedTextField();
        jSeparator9 = new javax.swing.JSeparator();
        StatementDateLabel3 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        StatementDateLabel4 = new javax.swing.JLabel();
        RAmount = new javax.swing.JFormattedTextField();
        jSeparator11 = new javax.swing.JSeparator();
        StatementDateLabel5 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        StatementDateLabel6 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        StatementDateLabel7 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        StatementDateLabel8 = new javax.swing.JLabel();
        RNotes = new javax.swing.JFormattedTextField();
        jSeparator15 = new javax.swing.JSeparator();
        StatementDateLabel9 = new javax.swing.JLabel();
        RUserId = new javax.swing.JFormattedTextField();
        jSeparator16 = new javax.swing.JSeparator();
        RCategory = new javax.swing.JComboBox<>();
        RFrequency = new javax.swing.JComboBox<>();
        RStartDate = new javax.swing.JFormattedTextField();
        REndDate = new javax.swing.JFormattedTextField();
        jPanel14 = new javax.swing.JPanel();
        MonthlyStatementLabel1 = new javax.swing.JLabel();
        StatementDateLabel1 = new javax.swing.JLabel();
        TransId = new javax.swing.JFormattedTextField();
        jSeparator17 = new javax.swing.JSeparator();
        StatementDateLabel10 = new javax.swing.JLabel();
        TransAmount = new javax.swing.JFormattedTextField();
        jSeparator18 = new javax.swing.JSeparator();
        StatementDateLabel11 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        StatementDateLabel12 = new javax.swing.JLabel();
        StatementDateLabel13 = new javax.swing.JLabel();
        ExpenseName13 = new javax.swing.JFormattedTextField();
        jSeparator21 = new javax.swing.JSeparator();
        StatementDateLabel14 = new javax.swing.JLabel();
        TransOneTimeName = new javax.swing.JFormattedTextField();
        jSeparator22 = new javax.swing.JSeparator();
        StatementDateLabel15 = new javax.swing.JLabel();
        TransUserId = new javax.swing.JFormattedTextField();
        jSeparator23 = new javax.swing.JSeparator();
        ExpenseSave1 = new javax.swing.JButton();
        TransCategory = new javax.swing.JComboBox<>();
        jSeparator24 = new javax.swing.JSeparator();
        TransDate = new javax.swing.JFormattedTextField();
        StatementDateLabel16 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryTable = new javax.swing.JTable();
        HistoryUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Budget Buddy");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(252, 68, 69));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 0, 140, 610));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your information:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/morganmacdonald/Downloads/desktop-3239677_1280.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 90));

        jTabbedPane3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        RId.setBackground(new java.awt.Color(51, 51, 51));
        RId.setBorder(null);
        RId.setForeground(new java.awt.Color(255, 255, 255));
        RId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        RId.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        RSave.setBackground(new java.awt.Color(252, 68, 69));
        RSave.setText("Save");
        RSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RSaveActionPerformed(evt);
            }
        });

        MonthlyStatementLabel.setBackground(new java.awt.Color(237, 245, 227));
        MonthlyStatementLabel.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        MonthlyStatementLabel.setForeground(new java.awt.Color(85, 188, 201));
        MonthlyStatementLabel.setText("Recurring Expenses/Income:");

        StatementDateLabel.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel.setText("Recurring Id");

        StatementDateLabel2.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel2.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel2.setText("Source Name");

        SourceName.setBackground(new java.awt.Color(51, 51, 51));
        SourceName.setBorder(null);
        SourceName.setForeground(new java.awt.Color(255, 255, 255));
        SourceName.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        SourceName.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel3.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel3.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel3.setText("Frequency");

        StatementDateLabel4.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel4.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel4.setText("Amount (if expense, make negative)");

        RAmount.setBackground(new java.awt.Color(51, 51, 51));
        RAmount.setBorder(null);
        RAmount.setForeground(new java.awt.Color(255, 255, 255));
        RAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        RAmount.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel5.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel5.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel5.setText("Start Date (yyyymmdd)");

        StatementDateLabel6.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel6.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel6.setText("End Date (yyyymmdd)");

        StatementDateLabel7.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel7.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel7.setText("Category");

        StatementDateLabel8.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel8.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel8.setText("Notes");

        RNotes.setBackground(new java.awt.Color(51, 51, 51));
        RNotes.setBorder(null);
        RNotes.setForeground(new java.awt.Color(255, 255, 255));
        RNotes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        RNotes.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel9.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel9.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel9.setText("User Id");

        RUserId.setBackground(new java.awt.Color(51, 51, 51));
        RUserId.setBorder(null);
        RUserId.setForeground(new java.awt.Color(255, 255, 255));
        RUserId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        RUserId.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        RCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "pay", "gift", "alimony", "child support", "winnings", "rent", "car", "insurance", "utilities", "food" }));

        RFrequency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "weekly", "bi-weekly", "monthly", "6 months", "quarterly" }));

        RStartDate.setBackground(new java.awt.Color(51, 51, 51));
        RStartDate.setBorder(null);
        RStartDate.setForeground(new java.awt.Color(255, 255, 255));
        try {
            RStartDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        RStartDate.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        REndDate.setBackground(new java.awt.Color(51, 51, 51));
        REndDate.setBorder(null);
        REndDate.setForeground(new java.awt.Color(255, 255, 255));
        try {
            REndDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        REndDate.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(MonthlyStatementLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RSave))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel6)
                                    .addComponent(REndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel)
                                    .addComponent(RId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel9)
                                    .addComponent(RUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel2)
                                    .addComponent(SourceName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel4)
                                    .addComponent(RAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel8)
                                    .addComponent(StatementDateLabel3)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel7)
                                    .addComponent(RCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonthlyStatementLabel)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(StatementDateLabel8)
                                    .addComponent(StatementDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatementDateLabel3)
                    .addComponent(StatementDateLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(StatementDateLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatementDateLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SourceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatementDateLabel4)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatementDateLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(RSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatementDateLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(REndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Recurring", jPanel2);

        jPanel14.setBackground(new java.awt.Color(51, 51, 51));

        MonthlyStatementLabel1.setBackground(new java.awt.Color(237, 245, 227));
        MonthlyStatementLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        MonthlyStatementLabel1.setForeground(new java.awt.Color(85, 188, 201));
        MonthlyStatementLabel1.setText("Transactions:");

        StatementDateLabel1.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel1.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel1.setText("Transaction Id");

        TransId.setBackground(new java.awt.Color(51, 51, 51));
        TransId.setBorder(null);
        TransId.setForeground(new java.awt.Color(255, 255, 255));
        TransId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TransId.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel10.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel10.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel10.setText("Amount (if expense, make negative)");

        TransAmount.setBackground(new java.awt.Color(51, 51, 51));
        TransAmount.setBorder(null);
        TransAmount.setForeground(new java.awt.Color(255, 255, 255));
        TransAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TransAmount.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel11.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel11.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel11.setText("Date (yyyymmdd)");

        StatementDateLabel12.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel12.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel12.setText("Category");

        StatementDateLabel13.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel13.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel13.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel13.setText("Recurring Id");

        ExpenseName13.setBackground(new java.awt.Color(51, 51, 51));
        ExpenseName13.setBorder(null);
        ExpenseName13.setForeground(new java.awt.Color(255, 255, 255));
        ExpenseName13.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        ExpenseName13.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel14.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel14.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel14.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel14.setText("One Time Transaction Name");

        TransOneTimeName.setBackground(new java.awt.Color(51, 51, 51));
        TransOneTimeName.setBorder(null);
        TransOneTimeName.setForeground(new java.awt.Color(255, 255, 255));
        TransOneTimeName.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TransOneTimeName.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel15.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel15.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel15.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel15.setText("User Id");

        TransUserId.setBackground(new java.awt.Color(51, 51, 51));
        TransUserId.setBorder(null);
        TransUserId.setForeground(new java.awt.Color(255, 255, 255));
        TransUserId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TransUserId.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        ExpenseSave1.setBackground(new java.awt.Color(252, 68, 69));
        ExpenseSave1.setText("Save");
        ExpenseSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpenseSave1ActionPerformed(evt);
            }
        });

        TransCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "pay", "gift", "alimony", "child support", "winnings", "rent", "car", "insurance", "utilities", "food" }));

        TransDate.setBackground(new java.awt.Color(51, 51, 51));
        TransDate.setBorder(null);
        TransDate.setForeground(new java.awt.Color(255, 255, 255));
        try {
            TransDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TransDate.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        StatementDateLabel16.setBackground(new java.awt.Color(237, 245, 227));
        StatementDateLabel16.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        StatementDateLabel16.setForeground(new java.awt.Color(85, 188, 201));
        StatementDateLabel16.setText("(if applicable)");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TransOneTimeName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StatementDateLabel1)
                                    .addComponent(TransId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ExpenseName13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel13)
                                    .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TransUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel15)
                                    .addComponent(StatementDateLabel14)
                                    .addComponent(StatementDateLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExpenseSave1)
                                    .addComponent(TransAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel10)
                                    .addComponent(StatementDateLabel11)
                                    .addComponent(TransDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatementDateLabel12)
                                    .addComponent(TransCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(MonthlyStatementLabel1))
                .addGap(37, 37, 37))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MonthlyStatementLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(StatementDateLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TransId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatementDateLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExpenseName13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(StatementDateLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TransUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatementDateLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(StatementDateLabel16))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(StatementDateLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TransAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StatementDateLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TransDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StatementDateLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TransCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExpenseSave1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TransOneTimeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Transaction", jPanel14);

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));

        HistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction Id", "Amount", "Date", "Category", "One Time Name", "User Id"
            }
        ));
        jScrollPane1.setViewportView(HistoryTable);

        HistoryUpdate.setBackground(new java.awt.Color(252, 68, 69));
        HistoryUpdate.setText("Update");
        HistoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(HistoryUpdate)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HistoryUpdate)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("History", jPanel15);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 570, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RSaveActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://localhost:5432/Budget Builder";
            String user = "postgres";
            String password = "gar18";
            
            conn = DriverManager.getConnection(url, user, password);
            String sqlQuery = "INSERT INTO public.\"RecurringTable\"(\"RecurringId\", \"SourceName\", \"Amount\", \"Note\", \"UserId\", \"frequency_id\", \"Category\", \"StartDate\", \"EndDate\") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sqlQuery);
            //RecurringId
            pst.setInt(1, Integer.parseInt(RId.getText()));
            //SourceName
            pst.setString(2, SourceName.getText());
            //Amount
            pst.setInt(3, Integer.parseInt(RAmount.getText()));
            //Notes
            pst.setString(4, RNotes.getText());
            //UserId
            pst.setInt(5, Integer.parseInt(RUserId.getText()));
            //Frequency
            String frequency;
            frequency = RFrequency.getSelectedItem().toString();
            pst.setString(6, frequency);
            //Categroy
            String category;
            category = RCategory.getSelectedItem().toString();
            pst.setString(7, category);
            //StartDate
                //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                //String date = sdf.format(RStartDate.getDate());
                //pst.setInt(4, Integer.parseInt(date));
            pst.setInt(8, Integer.parseInt(RStartDate.getText()));
            //EndDate
                //SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
                //String date2 = sdf2.format(REndDate.getDate());
                //pst.setInt(5, Integer.parseInt(date2));
            pst.setInt(9, Integer.parseInt(REndDate.getText()));
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "saved");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_RSaveActionPerformed

    private void ExpenseSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpenseSave1ActionPerformed
        try{
            Class.forName("org.postgresql.Driver");
            String url = "jdbc:postgresql://localhost:5432/Budget Builder";
            String user = "postgres";
            String password = "gar18";
            
            conn = DriverManager.getConnection(url, user, password);
            String sqlQuery = "INSERT INTO public.\"Transactions\"(\"TransactionId\", \"Amount\", \"OneTimeName\", \"UserId\", \"Category\", \"Date\") VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sqlQuery);
            //TransId
            pst.setInt(1, Integer.parseInt(TransId.getText()));
            //TransAmount
            pst.setInt(2, Integer.parseInt(TransAmount.getText()));
            //OneTimeName
            pst.setString(3, TransOneTimeName.getText());
            //UserId
            pst.setInt(4, Integer.parseInt(TransUserId.getText()));
            //Category
            String category;
            category = TransCategory.getSelectedItem().toString();
            pst.setString(5, category);
            //TransDate
                //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                //String date = sdf.format(TransDate.getDate());
                //pst.setString(3, date);
            pst.setInt(6, Integer.parseInt(TransDate.getText()));
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "saved");
        } catch(Exception e){
           JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_ExpenseSave1ActionPerformed

    private void HistoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)HistoryTable.getModel();
        model.setRowCount(0);
        show_trans();
    }//GEN-LAST:event_HistoryUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BudgetBuddyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BudgetBuddyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BudgetBuddyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BudgetBuddyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BudgetBuddyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ExpenseName13;
    private javax.swing.JButton ExpenseSave1;
    private javax.swing.JTable HistoryTable;
    private javax.swing.JButton HistoryUpdate;
    private javax.swing.JLabel MonthlyStatementLabel;
    private javax.swing.JLabel MonthlyStatementLabel1;
    private javax.swing.JFormattedTextField RAmount;
    private javax.swing.JComboBox<String> RCategory;
    private javax.swing.JFormattedTextField REndDate;
    private javax.swing.JComboBox<String> RFrequency;
    private javax.swing.JFormattedTextField RId;
    private javax.swing.JFormattedTextField RNotes;
    private javax.swing.JButton RSave;
    private javax.swing.JFormattedTextField RStartDate;
    private javax.swing.JFormattedTextField RUserId;
    private javax.swing.JFormattedTextField SourceName;
    private javax.swing.JLabel StatementDateLabel;
    private javax.swing.JLabel StatementDateLabel1;
    private javax.swing.JLabel StatementDateLabel10;
    private javax.swing.JLabel StatementDateLabel11;
    private javax.swing.JLabel StatementDateLabel12;
    private javax.swing.JLabel StatementDateLabel13;
    private javax.swing.JLabel StatementDateLabel14;
    private javax.swing.JLabel StatementDateLabel15;
    private javax.swing.JLabel StatementDateLabel16;
    private javax.swing.JLabel StatementDateLabel2;
    private javax.swing.JLabel StatementDateLabel3;
    private javax.swing.JLabel StatementDateLabel4;
    private javax.swing.JLabel StatementDateLabel5;
    private javax.swing.JLabel StatementDateLabel6;
    private javax.swing.JLabel StatementDateLabel7;
    private javax.swing.JLabel StatementDateLabel8;
    private javax.swing.JLabel StatementDateLabel9;
    private javax.swing.JFormattedTextField TransAmount;
    private javax.swing.JComboBox<String> TransCategory;
    private javax.swing.JFormattedTextField TransDate;
    private javax.swing.JFormattedTextField TransId;
    private javax.swing.JFormattedTextField TransOneTimeName;
    private javax.swing.JFormattedTextField TransUserId;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
